arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
synthetic-package: false
nullable-getter: false
# P96 S233: added es, fr, de, ja, zh, ar stubs (2026-04-24)
